---
- name: Uso del cliente FTP en línea de comandos
  hosts: tierra
  become: yes
  tasks:
    - name: Crear usuario pepe si no existe
      user:
        name: pepe
        state: present
        create_home: yes

    - name: Crear directorio /home/pepe/pruebasFTP
      file:
        path: /home/pepe/pruebasFTP
        state: directory
        owner: pepe
        group: pepe
        mode: '0755'

    - name: Crear archivo datos1.txt con contenido
      ansible.builtin.copy:
        content: |
          Este es un archivo de prueba para el FTP.
        dest: /home/pepe/pruebasFTP/datos1.txt
        owner: pepe
        group: pepe
        mode: '0644'

