---
- hosts: tierra
  become: true
  tasks:
    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar Bind9 y utilidades
      apt:
        name:
          - bind9
          - bind9utils
          - bind9-doc
        state: present

    - name: Copiar el archivo named.conf.local desde la máquina remota
      copy:
        src: /vagrant/named.conf.local
        dest: /etc/bind/named.conf.local
        remote_src: yes

    - name: Copiar el archivo named.conf.options desde la máquina remota
      copy:
        src: /vagrant/named.conf.options
        dest: /etc/bind/named.conf.options
        remote_src: yes

    - name: Copiar la zona db.sistema.sol desde la máquina remota
      copy:
        src: /vagrant/db.sistema.sol
        dest: /var/lib/bind/db.sistema.sol
        owner: bind
        group: bind
        mode: '0644'
        remote_src: yes

    - name: Copiar la zona db.192.168.57 desde la máquina remota
      copy:
        src: /vagrant/db.192.168.57
        dest: /var/lib/bind/db.192.168.57
        owner: bind
        group: bind
        mode: '0644'
        remote_src: yes

    - name: Configurar resolv.conf desde la máquina remota
      copy:
        src: /vagrant/resolv.conf
        dest: /etc/resolv.conf
        remote_src: yes

    - name: Reiniciar el servicio Bind9
      service:
        name: bind9
        state: restarted

- hosts: clientes
  become: true
  tasks:
    - name: Configurar resolv.conf en clientes
      copy:
        src: /vagrant/resolv.conf
        dest: /etc/resolv.conf
        remote_src: yes
